services:
  db:
    image: postgres:13
    container_name: property_reviews_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: property_reviews
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: property_reviews_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: property_reviews_api
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"

volumes:
  db_data:
